### ISSUE TITLE
Cannot install 0.8.0 in JRuby

### ISSUE THREAD

**Issue by katafrakt** [dry-rb/dry-container#78]
## Describe the bug

When attempting to install dry-container 0.8.0 on JRuby, I'm consistently getting an error:

```
ERROR:  Error installing dry-container:
	dry-container-0.8.0 requires Ruby version >= 2.6.0. The current ruby version is 2.5.7.0.
```

`dry-core`, which has similar code in the gemspec, installs fine.

## To Reproduce

1. Install JRuby
2. Try to install dry-container with `jruby -S gem install dry-container --version 0.8.0`

## Expected behavior

`dry-container` 0.8.0 is installed

## My environment

I checked it with JRuby versions 9.2.16.0 and 9.2.17.0 on Linux and Mac. Tried `gem update --system` but did not help.

The only thing I see is that in [dry-container rubygems page](https://rubygems.org/gems/dry-container) required ruby version on the right is `>= 2.6.0` while [with dry-core](https://rubygems.org/gems/dry-core) it says `>= 2.5.0`. So maybe a wrong file was pushed to RubyGems somehow?

**Comment by solnic** [comment]
@katafrakt our spec suite passes so this is confusing. Are you sure you're using the latest version of jruby?

**Comment by katafrakt** [comment]
@solnic yes, I am sure. Also, the test suite passes for me too when I clone the repo. It works when I set source to the git repo via

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'dry-container', git: 'https://github.com/dry-rb/dry-container'
end
```

but not for 0.8.0 (with bundler or without)

As for my JRuby version:

```
❯ ruby -v
jruby 9.2.17.0 (2.5.8) 2021-03-29 84d363da97 OpenJDK 64-Bit Server VM 25.282-b00 on 1.8.0_282-bre_2021_01_20_16_37-b00 +jit [darwin-x86_64]
```

**Comment by katafrakt** [comment]
I downloaded the actual files from rubygems and looked at `metadata` files. For `dry-core` it says:

```
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 2.5.0
```

while for `dry-container` the relevant lines say

```
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 2.6.0
```

So yeah, I suspect the problem does not lie in the code but in the file that has been pushed to rubygems.
